[package]
name = "ripcal"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0"
license-file = "LICENSE"
description = "Convert IP address strings to/from integers"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
