[package]
name = "ripcal"
version = "0.2.1"
edition = "2021"
license = "GPL-2.0"
description = "Convert IP address strings to/from integers"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
